GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/someInvalidId

###
PUT http://localhost:3001/api/persons/64e1e0fbc9bc699db8200f94
content-type: application/json

{
    "name": "b"
}